export const CREATE_MILESTONES = "CREATE_MILESTONES";
export const DELETE_MILESTONES = "DELETE_MILESTONES";
export const CREATE_MILESTONES_FOR_PROJ_DETS = "CREATE_MILESTONES_FOR_PROJ_DETS";
export const UPDATE_MILESTONE = "UPDATE_MILESTONE";

export const SUBMIT = "SUBMIT";
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";
export const UPDATE_TO_FIREBASE = "UPDATE_TO_FIREBASE";

export const RENDER_MILESTONES = "RENDER_MILESTONES";

export const STARTING_REQUEST = "STARTING_REQUEST";
export const FINISHED_REQUEST = "FINISHED_REQUEST";

export const PROJECT_DETS_STARTING_REQUEST = "PROJECT_DETS_STARTING_REQUEST";
export const PROJECT_DETS_FINISHED_REQUEST = "PROJECT_DETS_FINISHED_REQUEST";
export const UPDATE_MILESTONE_FOR_PROJ_DETS = "UPDATE_MILESTONE_FOR_PROJ_DETS";
export const UPDATE_DETS_TO_FIREBASE = "UPDATE_DETS_TO_FIREBASE";

export const PROGRESS_DISPLAY_STARTING_REQUEST = "PROGRESS_DISPLAY_STARTING_REQUEST";
export const PROGRESS_DISPLAY_FINISHED_REQUEST = "PROGRESS_DISPLAY_FINISHED_REQUEST";

export const ARCHIVE_TO_FB = "ARCHIVE_TO_FB";
export const DONE_ARCHIVE_TO_FB ="DONE_ARCHIVE_TO_FB";
