export const CREATE_MILESTONES = "CREATE_MILESTONES";
export const CREATE_MILESTONES_FOR_PROJ_DETS = "CREATE_MILESTONES_FOR_PROJ_DETS";
export const UPDATE_MILESTONE = "UPDATE_MILESTONE";
export const UPDATE_MILESTONR_FOR_PROJ_DETS = "UPDATE_MILESTONR_FOR_PROJ_DETS";

export const SUBMIT = "SUBMIT";
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";
export const UPDATE_TO_FIREBASE = "UPDATE_TO_FIREBASE";

export const RENDER_MILESTONES = "RENDER_MILESTONES";

export const STARTING_REQUEST = "STARTING_REQUEST";
export const FINISHED_REQUEST = "FINISHED_REQUEST";

export const PROJECT_DETS_STARTING_REQUEST = "PROJECT_DETS_STARTING_REQUEST";
export const PROJECT_DETS_FINISHED_REQUEST = "PROJECT_DETS_FINISHED_REQUEST";
export const UPDATE_FORM_DATA ="UPDATE_FORM_DATA";
